use_frameworks!
inhibit_all_warnings!

target 'SDWebImagePhotosPlugin_Example' do
  platform :ios, '9.0'
  pod 'SDWebImagePhotosPlugin', :path => '../'

  target 'SDWebImagePhotosPlugin_Tests' do
    inherit! :search_paths
    pod 'Expecta'
    
  end
end

target 'SDWebImagePhotosPlugin_Example macOS' do
  platform :osx, '10.13'
  pod 'SDWebImagePhotosPlugin', :path => '../'
end